version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./symfony/public:/home/wwwroot/sf4/public # decomment when symfony is installed
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: sf4_mysql
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - ./symfony:/home/wwwroot/sf4 #only for sf install
          - ./sf_install.sh:/home/wwwroot/sf4/sf_install.sh
          - composervendor:/home/wwwroot/sf4/vendor
         # - ./symfony/bin:/home/wwwroot/sf4/bin # decomment when symfony is installed
         # - ./symfony/config:/home/wwwroot/sf4/config  # decomment when symfony is installed
         # - ./symfony/public:/home/wwwroot/sf4/public # decomment when symfony is installed
         # - ./symfony/src:/home/wwwroot/sf4/src # decomment when symfony is installed
         # - ./symfony/.env:/home/wwwroot/sf4/.env # decomment when symfony is installed
         # - ./symfony/var/log:/home/wwwroot/sf4/log:cached # decomment when symfony is installed
         # - ./symfony/composer.json:/home/wwwroot/sf4/composer.json # decomment when symfony is installed
         # - ./symfony/composer.lock:/home/wwwroot/sf4/composer.lock # decomment when symfony is installed
         # - ./symfony/sf_install.sh:/home/wwwroot/sf4/sf_install.sh # decomment when symfony is installed
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8001:80
volumes:
    dbdata:
        driver: local
    composervendor:
        driver: local
